### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by montao** [bstarynk/bismon#1]
When I try to install the dependencies (gtk 3.22) I get this error message and the rest is down the hole in endless dependency configurations. Could we please organize build instructions from a clean ubuntu 16.04 or some container for sombody who just wants to try the program...
```

configure: error: Package requirements (glib-2.0 >= 2.49.4    atk >= 2.15.1    pango >= 1.37.3    cairo >= 1.14.0    cairo-gobject >= 1.14.0    gdk-pixbuf-2.0 >= 2.30.0) were not met:

Requested 'glib-2.0 >= 2.49.4' but version of GLib is 2.48.2

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BASE_DEPENDENCIES_CFLAGS
and BASE_DEPENDENCIES_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details
```

**Comment by bstarynk** [comment]
You might try some earlier version of gtk3, if your distribution is packaging it.

As I told you privately the GTK interface is supposed to die, and will be replaced by some web interface using libonion. So I probably won't fix that particular issue.
