### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by AntonOsika** [bstarynk/bismon#4]
Do you have an example of any concrete use case that Bismon will be able to solve that is not possible (or suboptimal) to solve with similar tools?

**Comment by bstarynk** [comment]
Not yet. Wait a few months

**Comment by bstarynk** [comment]
Read the [Bismon Chariot draft report](http://starynkevitch.net/Basile/bismon-chariot-doc.pdf); which is evolving quite often.
